# Auto-generated by the bruce-tui release workflow — do not edit by hand.
# Template: https://github.com/soydanielsierradev/bruce-tui/blob/main/packaging/homebrew/bruce.rb
class Bruce < Formula
  desc "Terminal workspace for Claude Code"
  homepage "https://github.com/soydanielsierradev/bruce-tui"
  version "0.11.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/soydanielsierradev/bruce-tui/releases/download/v0.11.1/bruce-aarch64-apple-darwin.tar.gz"
      sha256 "c0c9b4371071d50e200cd8ee68cab71126d429505a665a6009836511624bf44d"
    end
    on_intel do
      url "https://github.com/soydanielsierradev/bruce-tui/releases/download/v0.11.1/bruce-x86_64-apple-darwin.tar.gz"
      sha256 "9b0252d035a7da9adbf8aa5d25784c6f50434384b3627de9c4e99d0a584edb9c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/soydanielsierradev/bruce-tui/releases/download/v0.11.1/bruce-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "c23e6fd3497e0986ac7821fcd8359199fb10555da861bd229a04bd89fed70a9c"
    end
  end

  def install
    bin.install "bruce"
  end

  def caveats
    <<~CAVEAT
      Bruce runs the Claude CLI inside its workspace. Install Claude Code and
      make sure `claude` is on your PATH: https://docs.claude.com/claude-code
    CAVEAT
  end

  test do
    assert_match "bruce", shell_output("#{bin}/bruce --version")
  end
end
