# Auto-generated by the bruce-tui release workflow — do not edit by hand.
# Template: https://github.com/soydanielsierradev/bruce-tui/blob/main/packaging/homebrew/bruce.rb
class Bruce < Formula
  desc "Terminal workspace for Claude Code"
  homepage "https://github.com/soydanielsierradev/bruce-tui"
  version "0.11.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/soydanielsierradev/bruce-tui/releases/download/v0.11.0/bruce-aarch64-apple-darwin.tar.gz"
      sha256 "0e1435e740801a84f8434ab77e6d871eb62edb3ce5736cbea994a936ea03e895"
    end
    on_intel do
      url "https://github.com/soydanielsierradev/bruce-tui/releases/download/v0.11.0/bruce-x86_64-apple-darwin.tar.gz"
      sha256 "42191790dcd0b67ee6aa7394eb5ca5b64680cc8e37de154a60707cadd5da0544"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/soydanielsierradev/bruce-tui/releases/download/v0.11.0/bruce-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "d986c16622905c348dc96054c043aa6e3c5e29cf0d1439735d20fee67dde31b7"
    end
  end

  def install
    bin.install "bruce"
  end

  def caveats
    <<~CAVEAT
      Bruce runs the Claude CLI inside its workspace. Install Claude Code and
      make sure `claude` is on your PATH: https://docs.claude.com/claude-code
    CAVEAT
  end

  test do
    assert_match "bruce", shell_output("#{bin}/bruce --version")
  end
end
