# Auto-generated by the bruce-tui release workflow — do not edit by hand.
# Template: https://github.com/soydanielsierradev/bruce-tui/blob/main/packaging/homebrew/bruce.rb
class Bruce < Formula
  desc "Terminal workspace for Claude Code"
  homepage "https://github.com/soydanielsierradev/bruce-tui"
  version "0.14.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/soydanielsierradev/bruce-tui/releases/download/v0.14.0/bruce-aarch64-apple-darwin.tar.gz"
      sha256 "a8c9b407875afff27af62ceccac5839e9eddb05dbaa1bfb2d545cbcb65fa1eae"
    end
    on_intel do
      url "https://github.com/soydanielsierradev/bruce-tui/releases/download/v0.14.0/bruce-x86_64-apple-darwin.tar.gz"
      sha256 "ee53332b3596ffe85eb53f7595c43f4dac0ad04abd36a5fc9211529aa25d371d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/soydanielsierradev/bruce-tui/releases/download/v0.14.0/bruce-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "9f537615039e0ce7d93bea66dccd3a57f91f06761d44a1f60c078234170dc833"
    end
  end

  def install
    bin.install "bruce"
  end

  def caveats
    <<~CAVEAT
      Bruce runs the Claude CLI inside its workspace. Install Claude Code and
      make sure `claude` is on your PATH: https://docs.claude.com/claude-code
    CAVEAT
  end

  test do
    assert_match "bruce", shell_output("#{bin}/bruce --version")
  end
end
